Improve areAreas speed
claeis/iox-ili pull request #105
Opened 2022-04-04 09:38 UTC by patrickackermann

Ref: https://github.com/claeis/ilivalidator/issues/308

2022-04-05 14:40 UTC, Philippluca requested changes

2022-04-05 14:40 UTC, Philippluca commented on src/main/java/ch/interlis/iox_j/validator/Validator.java
> +	private Map<Evaluable, Value> functions=new HashMap<Evaluable, Value>();
Q: Hat die Änderung Auswirkungen auf IoxPlugins? Bzw. profitieren Custom-Functions auch von Caching?

2022-04-06 10:32 UTC, patrickackermann commented on src/main/java/ch/interlis/iox_j/validator/Validator.java
> +	private Map<Evaluable, Value> functions=new HashMap<Evaluable, Value>();
Internen Funktionen wird dieser Cache beim evaluieren als Argument übergeben. IoxPlugins bekommen keinen Zugang zu diesem Cache und da er `private` ist sollten sie auch nicht darauf zugreifen. Wenn Custom-Functions etwas cachen möchten müssen sie einen eigenen Cache erstellen/verwalten.

2022-04-07 13:01 UTC, patrickackermann commented on src/test/java/ch/interlis/iox_j/validator/Function23Test.java
> +	// Es wird getestet, dass die erwarteten Fehler ausgegeben werden, wenn es Objekte von verschiedenen areAreas Constraints hat.
Ich habe die Beschreibung angepasst.

2022-04-07 16:15 UTC, Philippluca approved these changes

2022-04-20 13:31 UTC, merged