Optionally add constraint definition to error log
claeis/iox-ili pull request #111
Opened 2022-06-23 07:17 UTC by patrickackermann

see: Improve Validation Output https://github.com/opengisch/QgisModelBaker/issues/620

This change relies on changes from https://github.com/claeis/iox-ili/pull/109 in the _ErrorMsg23Test.java_ test class.

2022-06-23 09:12 UTC, claeis requested changes
Es fehlt ein Test, der die neue Funktionalität (isVerbose getDispname) testet.

2022-06-23 09:12 UTC, claeis commented on src/main/java/ch/interlis/iox_j/validator/Validator.java
> +		if (ValidationConfig.TRUE.equals(settings.getValue(CONFIG_VERBOSE))) {
Einmal als globales Feld auswerten, so dass hier nur noch (if(isVerbose){ nötig ist.

2022-06-24 14:22 UTC, patrickackermann commented
> Es fehlt ein Test, der die neue Funktionalität (isVerbose getDispname) testet.

Im _ErrorMsg23Test.java_ habe ich Tests erstellt, die die generierten Log Messages mit/ohne verbose für verschiedene Constraints testen. Reicht das nicht aus?

https://github.com/GeoWerkstatt/iox-ili/blob/18239f0bf336e217cf0ecc1ee587865f86dc5bc9/src/test/java/ch/interlis/iox_j/validator/ErrorMsg23Test.java#L333-L419

2022-06-25 09:55 UTC, claeis commented
ok, kann aber erst mergen wenn bei RP109 setDefaultCoord weg ist

2022-06-30 12:29 UTC, claeis approved these changes

2022-06-30 12:56 UTC, merged