Add (BASKET) support for UNIQUE and SET CONSTRAINTS
claeis/iox-ili pull request #119
Opened 2023-09-27 16:40 UTC by Philippluca

REF: [ILI2.4 Eindeutigkeitsbedingungen auf den einzelnen Transfer#379](https://github.com/claeis/ilivalidator/issues/379)

2023-09-28 09:51 UTC, Philippluca commented on src/main/java/ch/interlis/iox_j/validator/Validator.java
> +			if(setConstraint.getBasket() && setConstraints.get(setConstraint) != null){
Beim UniqueConstrait sammeln kann immer ein Set instanziiert werden, da immer mindestens 1 Objekt existiert. Ohne kann ein Unique constraint nie verletzt werden. Beim Set Constraint wird `null `noch als Marker für keine gefundenen Objekte benutzt, welcher beim evaluieren vom SetConstraint relevant ist. Daher auch der Bug, dass SET Constraints ohne Objekte nicht evaluiert werden. Siehe https://github.com/claeis/iox-ili/pull/118.

2023-09-28 09:53 UTC, Philippluca commented on src/test/java/ch/interlis/iox_j/validator/LogCollectorAssertions.java
> +        Assert.assertEquals( String.format("Wrong number of error logs containing <%s> found.", text), count, CountOccurrences(text, logCollector.getErrs()));
Diese info wird bereits von `Assert.assertEquals` angefügt. Es wurde eher missverständlich dupliziert.

2023-10-18 13:46 UTC, claeis requested changes

2023-10-18 13:46 UTC, claeis commented on src/main/java/ch/interlis/iox_j/validator/Validator.java
> +	private void UpdateCurrentBasket(String basketId) {
Funktionsnamen starten mit Kleinbuchstaben

2023-11-14 07:24 UTC, merged