ILI2.4 Constraints zu Domains
claeis/iox-ili pull request #121
Opened 2023-10-16 08:30 UTC by Philippluca

Ref: https://github.com/claeis/ilivalidator/issues/378

2023-10-17 08:04 UTC, patrickackermann approved these changes

2023-10-17 15:03 UTC, Philippluca commented on src/main/java/ch/interlis/iox_j/validator/Validator.java
> +		} else if(expression instanceof ParameterValue) {
Es ist zu einfach da etwas zu übersehen. Mir fehlen da langsam die Nerven ohne Checkstyle.

2023-10-18 05:42 UTC, patrickackermann approved these changes

2023-11-14 07:44 UTC, claeis requested changes
bitte ```"Value"``` als Konstante definieren

2023-11-15 15:24 UTC, merged